# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bac9fa4901e47fedbb7eb78043ee9ff04f908cc9b1292c3e8691ef27bf748af73a1b44a29c7345eee010259c511016027c23402df2a8c66da0804fa8133e381

test:
  secret_key_base: 76658f4d0723f57108cfb7da61dd16d9b8f8db9f8bf8e2ad95f183120604f7fd45e80a2f09f8695d522db05dd4fd3c5354bcac0fe70373de64d64033a2a5af57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
